/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.bdavanzadas.banco;

import java.sql.Date;
import java.util.Calendar;
import java.util.Collections;
import java.util.Comparator;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.itson.bdavanzadas.bancodominio.Transaccion;
import org.itson.bdavanzadas.bancopersistencia.dao.IClientesDAO;
import org.itson.bdavanzadas.bancopersistencia.excepciones.PersistenciaException;

/**
 *
 * @author castr
 */
public class HistorialOperacionesForm extends javax.swing.JFrame {

    private final IClientesDAO clientesDAO;
    private long numCuentaCliente;
    static final Logger logger = Logger.getLogger(HistorialOperacionesForm.class.getName());
    Date fechaInicio, fechaFin;

    /**
     * Creates new form HistorialOperacionesForm
     */
    public HistorialOperacionesForm(IClientesDAO clientesDAO, long numCuentaCliente) {
        initComponents();
        this.numCuentaCliente = numCuentaCliente;
        this.clientesDAO = clientesDAO;
//        this.numCuentaCliente = numCuentaCliente;
        llenarTabla();
    }

    private void llenarTabla() {
        // Obtener la lista de transacciones
        List<Transaccion> listaHistorialOperaciones;
        this.fechaInicio = new Date(new GregorianCalendar(2024, Calendar.JANUARY, 1).getTimeInMillis());
        this.fechaFin = new Date(new GregorianCalendar().getTimeInMillis());
        try {
            listaHistorialOperaciones = clientesDAO.obtenerHistorialOperaciones(numCuentaCliente, fechaInicio, fechaFin);
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("ID Transacción");
            modelo.addColumn("Número de Cuenta Cliente");
            modelo.addColumn("Fecha");
            modelo.addColumn("Monto");
            modelo.addColumn("Estado");

            // Ordenar la lista de transacciones por fecha de manera descendente (de la más reciente a la más antigua)
            Collections.sort(listaHistorialOperaciones, Comparator.comparing(Transaccion::getFecha).reversed());

            // Agregar las transacciones al modelo de la tabla
            for (Transaccion transaccion : listaHistorialOperaciones) {
                Object[] fila = {
                    transaccion.getId(),
                    transaccion.getNumCuentaCliente(),
                    transaccion.getFecha(),
                    transaccion.getMonto(),
                    transaccion.getEstado()
                };
                modelo.addRow(fila);
            }

            // Configurar el modelo en la tabla
            jtblHistorialOperaciones.setModel(modelo);

        } catch (PersistenciaException e) {
            logger.log(Level.SEVERE, "Error al momento de la creación de la tabla", e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblHistorialOperaciones = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtblHistorialOperaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblHistorialOperaciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HistorialOperacionesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HistorialOperacionesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HistorialOperacionesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HistorialOperacionesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HistorialOperacionesForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblHistorialOperaciones;
    // End of variables declaration//GEN-END:variables
}
